// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dreamers.Ui.Models
{
    public partial class Booking
    {
        public int Id { get; set; }
        public int ExcursionId { get; set; }
        public int? PromoCodeId { get; set; }
        public string Key { get; set; }
        public int AdultsNumber { get; set; }
        public int ChildrenNumber { get; set; }
        public DateTime CheckIn { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Hotel { get; set; }
        public string Room { get; set; }
        public string PromoCodeDiscountValue { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalPrice { get; set; }
        public int Status { get; set; }
        public DateTime? DateCreated { get; set; }

        public virtual Excursion Excursion { get; set; }
    }
}