// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dreamers.Ui.Models
{
    public partial class ExcursionPhoto
    {
        public int Id { get; set; }
        public int? ExcursionId { get; set; }
        public string Photo { get; set; }

        public virtual Excursion Excursion { get; set; }
    }
}