// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dreamers.Ui.Models
{
    public partial class Review
    {
        public int Id { get; set; }
        public int ExcursionId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public DateTime? DateCreated { get; set; }
        public bool? IsAccepted { get; set; }
    }
}