// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dreamers.Ui.Models
{
    public partial class SocialNetworkLocalized
    {
        public int SocialNetworkId { get; set; }
        public int LanguageId { get; set; }
        public string Title { get; set; }

        public virtual Language Language { get; set; }
        public virtual SocialNetwork SocialNetwork { get; set; }
    }
}