// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Dreamers.Ui.Models
{
    public partial class SocialNetwork
    {
        public SocialNetwork()
        {
            SocialNetworkLocalizeds = new HashSet<SocialNetworkLocalized>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SocialNetworkLocalized> SocialNetworkLocalizeds { get; set; }
    }
}